import React from "react";
import Footer from "./footer";
import Header from "./header";
import { Poppins } from "@next/font/google";
import Head from "next/head";

interface PageProps {
  children: any;
}

const poppins = Poppins({
  weight: ["200", "300", "400", "600", "700", "800", "900"],
  subsets: ["latin"],
  style: ["normal", "italic"],
});

export default function Layout({ children }: PageProps) {
  return (
    <div className={poppins.className}>
      <Head>
        <title>Fastest Learn Course</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </div>
  );
}
